// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    public_commitment_fund
    (
        init => init
        create_commitment => create_commitment
        submit_proof => submit_proof
        finalize => finalize
        claim => claim
        cancel => cancel
        get_commitment => get_commitment
        get_total_ids => get_total_ids
        get_ids_page => get_ids_page
        get_commitments_batch => get_commitments_batch
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
